version: "2"
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ${DATADIR}:/grav
    - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: phpgd
    volumes:
    - ${DATADIR}:/grav
    - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
