version: "2"
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ${GRAVDIR}:/grav
    - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: 1101010/php7fpm4grav
    volumes:
    - ${GRAVDIR}:/grav
    - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
